import { UI, UIColor } from "@talla-ui/core";

/** @internal Default set of colors */
export default {
	transparent: new UIColor("transparent"),
	black: new UIColor("#000000"),
	darkerGray: new UIColor("#333333"),
	darkGray: new UIColor("#777777"),
	gray: new UIColor("#aaaaaa"),
	lightGray: new UIColor("#dddddd"),
	white: new UIColor("#ffffff"),
	slate: new UIColor("#667788"),
	lightSlate: new UIColor("#c0c8d0"),
	red: new UIColor("#ee3333"),
	orange: new UIColor("#ee9922"),
	yellow: new UIColor("#ddcc33"),
	lime: new UIColor("#99bb33"),
	green: new UIColor("#44aa44"),
	turquoise: new UIColor("#33aaaa"),
	cyan: new UIColor("#33bbbb"),
	blue: new UIColor("#2277ff"),
	violet: new UIColor("#8844ee"),
	purple: new UIColor("#aa4488"),
	magenta: new UIColor("#dd2299"),
	divider: UI.colors.background.text().alpha(0.15),
	accent: UI.colors.background.fg("#222222", "#777777"),
	background: UI.colors.white,
	shade: UI.colors.background.contrast(-0.05),
	text: UI.colors.background.text(),
	danger: UI.colors.red,
	success: UI.colors.green,
	link: UI.colors.blue,
} as Readonly<Record<UI.ColorName, UIColor>>;
