name: www-build
on:
  push:
    branches:
      - www
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/configure-pages@v5
      - run: npm ci
      - run: npm run setup
      - run: npm run build
      - run: npm run www-build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: "docs/_site"
      - uses: actions/deploy-pages@v4
        id: deployment
